# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bushers' Blog - A blog by an aspriring web developer
email: nickbushby1@gmail.com
description: A blog by UK based web developer Nick Bushby.
baseurl: '/blog' # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nickbushby1
github_username:  bushers
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Nick Bushby
      layout: "post"
      category: webdev
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

# Gems
gems: [jekyll-paginate]